version: '3.8'

services:
  justice_app:
    build: .
    container_name: justice_company_web
    restart: unless-stopped
    ports:
      - "4584:4584"
    environment:
      - PORT=4584
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - DEVELOPER_CHAT_ID=${DEVELOPER_CHAT_ID}
    volumes:
      - justice_data:/app/data

volumes:
  justice_data: