version: '3.8'

services:
  justice_app:
    build: .
    container_name: justice_company_web
    restart: unless-stopped
    ports:
      - "5411:5411"
    environment:
      - PORT=5411
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
    volumes:
      - ./config.json:/app/config.json